"""inital migration

Revision ID: 4d3e0a58767d
Revises: cb4d3a1dcdc1
Create Date: 2017-05-03 17:20:16.654112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d3e0a58767d'
down_revision = 'cb4d3a1dcdc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.drop_column('comments', 'disable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('disable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('comments', 'disabled')
    # ### end Alembic commands ###
